### ISSUE TITLE
Wrong Version when trying to connect locally on Windows

### ISSUE THREAD

**Issue by DjKniteX** [TreeflyGames/XtremeWorlds#1]
Downloaded latest version (1.9.8) on Windows 11

1. Installed PostgreSQL
2. Ran Server
3. Opened up Client
4. When trying to create account or login; receive wrong version error
5. Upon inspection on files; Client is at 1.9.0.8 and Server is 1.9.0.7

Expecting to be able to log in with no issue regarding versions

**Comment by Helladen** [comment]
Fixed in https://github.com/TreeflyGames/XtremeWorlds/commit/ef800e98cbcf23a73ac64382125534e6204d379f
