### ISSUE TITLE
Server window shows a player online after disconnecting

### ISSUE THREAD

**Issue by DjKniteX** [TreeflyGames/XtremeWorlds#3]
Version 1.9.0.8
OS: Windows 10

1. Start Server
2. Note the 0 Players Online on Windows Tab
3. Open Client and log in as any character 
4. Note the 1 Players Online on Server Tab
5. Log out
6. 1 Players Online is still visible on Server Tab

Expecting to see 0 Players Online

![image](https://github.com/user-attachments/assets/ce42e1a6-9e9e-42fb-99b8-2549ff4e8c5a)

**Comment by XerShade** [comment]
I figured out what is causing this, it should be fixed when I am able to push my changes to the main repo.
