### ISSUE TITLE
Expired Discord

### ISSUE THREAD

**Issue by Eliwynn** [TreeflyGames/XtremeWorlds#4]
Hi !

It seems the Discord invitation is expired.
Maybe you could make it again with no day limit ?

Thanks !

**Comment by Helladen** [comment]
The link works for me.

Try this new one I made.
https://discord.gg/ruZmPsmsZz

**Comment by Eliwynn** [comment]
Indeed, must be on my side.
I managed to make it work in private navigation.
Thanks !
