### ISSUE TITLE
Network error when making a character

### ISSUE THREAD

**Issue by DjKniteX** [TreeflyGames/XtremeWorlds#6]
OS: Windows 10
XW Version: 1.99

After logging in and in the progress of making a character a network error would pop up 

Steps to reproduced:
1. Login as normal
2. Create a new character
3. Wait a few seconds or trying to think of a name)
Pop up will appear here
Pop up will appear here if idle on character select screen

Expecting no issues when making a character:

Temp fix:
Going through account creation quickly or selecting a character quick

![image](https://github.com/user-attachments/assets/06e32bdd-af12-42c7-9629-c4defd13a966)
![image](https://github.com/user-attachments/assets/8505ea78-e506-4505-a83e-c25c01f3a463)

**Comment by Helladen** [comment]
Fixed https://github.com/TreeflyGames/XtremeWorlds/commit/2b2661f0bca5be3a5201f3440a578589ed29da99
